# .github/workflows/wake_up.yml
name: Wake up periodically
on:
  schedule:
    - cron: "0 0 */6 * *"  # 매 5일마다 실행, 자정에 실행
  workflow_dispatch:  # 수동 실행용
jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send request
        run: |
          curl --request POST --url https://bincha.vercel.app/login
